-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHEka8E8aHxmoD5nZ
VEAkoXy+uIPURS1GG/YmOLjU9MagCgYIKoZIzj0DAQehRANCAAQhBQIo+hzpwuR5
OVXXCJ84NfDBHGWZ3AffCurABupsn8jelQQaHKPkkRqf8xrZe8kwL9dYDHuVQ9Js
Bn0BwkYH
-----END PRIVATE KEY-----